# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rj5wWe0A53Rakbb-qoJycKJGBEp9rj6W
"""

!pip install tensorflow==2.12.1

from keras.models import load_model
from PIL import Image, ImageOps
import numpy as np

# Disable scientific notation
np.set_printoptions(suppress=True)

# Load the model (note: match exact filename)
model = load_model("keras_model.h5", compile=False)

# Load class labels
class_names = open("labels.txt", "r").readlines()

# Prepare the image
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
image = Image.open("a3.jpg").convert("RGB")
size = (224, 224)
image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
image_array = np.asarray(image)
normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
data[0] = normalized_image_array

# Make prediction
prediction = model.predict(data)
index = np.argmax(prediction)
class_name = class_names[index]
confidence_score = prediction[0][index]

# Output
print("Class:", class_name.strip())
print("Confidence Score:", round(confidence_score, 2))

import os
print(os.listdir())

from google.colab import files
uploaded = files.upload()